# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/aws-accounts/cloud-platform-aws/account"
    schedule:
      interval: "weekly"
      day: "sunday"
    rebase-strategy: "disabled"
  - package-ecosystem: "terraform"
    directory: "/terraform/aws-accounts/cloud-platform-aws/vpc"
    schedule:
      interval: "weekly"
      day: "sunday"
    rebase-strategy: "disabled"
  - package-ecosystem: "terraform"
    directory: "/terraform/aws-accounts/cloud-platform-aws/vpc/eks"
    schedule:
      interval: "weekly"
      day: "sunday"
    rebase-strategy: "disabled"
  - package-ecosystem: "terraform"
    directory: "/terraform/aws-accounts/cloud-platform-aws/vpc/eks/components"
    schedule:
      interval: "weekly"
      day: "sunday"
    rebase-strategy: "disabled"
  - package-ecosystem: "terraform"
    directory: "/terraform/aws-accounts/cloud-platform-aws/vpc/kops"
    schedule:
      interval: "weekly"
      day: "sunday"
    rebase-strategy: "disabled"
  - package-ecosystem: "terraform"
    directory: "/terraform/aws-accounts/cloud-platform-aws/vpc/kops/components"
    schedule:
      interval: "weekly"
      day: "sunday"
    rebase-strategy: "disabled"
  - package-ecosystem: "terraform"
    directory: "/terraform/aws-accounts/cloud-platform-dsd"
    schedule:
      interval: "weekly"
      day: "sunday"
    rebase-strategy: "disabled"
  - package-ecosystem: "terraform"
    directory: "/terraform/aws-accounts/cloud-platform-ephemeral-test/account"
    schedule:
      interval: "weekly"
      day: "sunday"
    rebase-strategy: "disabled"
  - package-ecosystem: "terraform"
    directory: "/terraform/aws-accounts/cloud-platform-ephemeral-test/vpc"
    schedule:
      interval: "weekly"
      day: "sunday"
    rebase-strategy: "disabled"
  - package-ecosystem: "terraform"
    directory: "/terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks"
    schedule:
      interval: "weekly"
      day: "sunday"
    rebase-strategy: "disabled"
  - package-ecosystem: "terraform"
    directory: "/terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks/components"
    schedule:
      interval: "weekly"
      day: "sunday"
    rebase-strategy: "disabled"
  - package-ecosystem: "terraform"
    directory: "/terraform/cross-account-IAM"
    schedule:
      interval: "weekly"
      day: "sunday"
    rebase-strategy: "disabled"
  - package-ecosystem: "terraform"
    directory: "/terraform/global-resources"
    schedule:
      interval: "weekly"
      day: "sunday"
    rebase-strategy: "disabled"
