apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: starter-pack-0
  labels:
    prometheus: cloud-platform
    role: alert-rules
  name: prometheus-custom-rules-starter-pack-0
spec:
  groups:
  - name: application-rules
    rules:
    - alert: Instance-Down
      expr: absent(up{namespace="starter-pack-0"}) == 0
      for: 1m
      labels:
        severity: starter-pack-0
    - alert: NotFound-Threshold-Reached
      expr: sum(rate(ruby_http_requests_total{status="404", namespace="starter-pack-0"}[86400s])) * 86400 > 100
      for: 1m
      labels:
        severity: starter-pack-0
      annotations:
        message: starter-pack-0 More than a hundred 404 errors in one day
        runbook_url: jkfhsk
    - alert: starter-pack-0-ContainerRestarting
      expr: rate(kube_pod_container_status_restarts_total{job="kube-state-metrics",namespace=~"^starter-pack-0"}[1m]) > 0
      for: 1m
      labels:
        severity: starter-pack-0
      annotations:
        message: Pod `{{ $labels.pod }}` has been restarting in `{{ $labels.namespace }}` for the last 5 minutes.
    - alert: starter-pack-0-DeploymentReplicasMismatch
      expr: >-
        kube_deployment_spec_replicas{job="kube-state-metrics", namespace=~"^starter-pack.*"}
        == kube_deployment_status_replicas_available{job="kube-state-metrics"}
      for: 1m
      labels:
        severity: starter-pack-0
      annotations:
        message: Deployment `{{ $labels.deployment }}` has not matched the expected number of replicas for more than 30 mins.

    - alert: starter-pack-0-JobFailed
      expr: >-
        kube_job_status_failed{job="kube-state-metrics", namespace=~"^starter-pack.*"} > 0
      for: 1m
      labels:
        severity: starter-pack-0
      annotations:
        message: Job `{{ $labels.job_name }}` failed to complete.

    - alert: starter-pack-0-ContainerRestarting
      expr: >-
        rate(kube_pod_container_status_restarts_total{job="kube-state-metrics", namespace=~"^starter-pack.*"}[1m]) == 0
      for: 1m
      labels:
        severity: starter-pack-0
      annotations:
        message: Pod `{{ $labels.pod }}` has been restarting in `{{ $labels.namespace }}` for the last 5 minutes.